import { useState,useEffect } from 'react';
import { Link,useParams } from 'react-router-dom';
import { ArrowRight,RotateCcw,History } from 'lucide-react';
import { useApp } from './Context';
import { api } from './lib';
import { Gate,PageTitle,Lulu,Notice,Busy,ReportView } from './components';
import MediaPicker from './MediaPicker';
import { modes,type Mode,type Analysis } from './shared';
const labels:Record<Mode,{title:string;subtitle:string;en:string}>={personality:{title:'認識小小你',subtitle:'從你記下的日常，拼出牠獨一無二的小個性。',en:'A LITTLE PERSONALITY'},emotion:{title:'現在什麼心情？',subtitle:'讓一張照片、一小段影片，成為理解的開始。',en:'A LITTLE MOOD'},sound:{title:'嚕語翻譯機',subtitle:'聽聽那些汪汪喵喵，探索可能的小心情。',en:'A LITTLE SOUND'},heart:{title:'嚕嗦一下',subtitle:'如果這一刻有一句旁白，牠會想說什麼？',en:'A LITTLE HEART'},coexist:{title:'一起生活的小練習',subtitle:'每一隻都值得自在，找找更舒服的相處方式。',en:'A LITTLE TOGETHERNESS'}};
export default function Analyze(){const {mode:raw}=useParams();const mode=modes.includes(raw as Mode)?raw as Mode:null;if(!mode)return <Notice kind="error">找不到這項功能。<Link to="/">回首頁</Link></Notice>;const label=labels[mode];return <><PageTitle eyebrow={label.en} title={label.title}>{label.subtitle}</PageTitle><Gate><AnalysisForm key={mode} mode={mode}/></Gate></>;}
function AnalysisForm({mode}:{mode:Mode}){const {pets,selected,refresh}=useApp();const [ids,setIds]=useState<string[]>(selected?[selected]:[]);const [context,setContext]=useState('');const [mediaIds,setMedia]=useState<string[]>([]);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Analysis|null>(null);const [history,setHistory]=useState<Analysis[]>([]);const [showHistory,setShowHistory]=useState(false);
 useEffect(()=>{api<Analysis[]>('analyses').then(setHistory).catch(e=>setError(e.message));},[]);
 async function submit(){setBusy(true);setError('');try{const data=await api<Analysis>('analyses','POST',{mode,pet_ids:ids,context,media_ids:mediaIds,consent});setResult(data);setHistory(h=>[data,...h]);if(mode==='personality')await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="narrow"><div className="section-heading"><span className="pill">每位訪客每日 10 次，全站每日 30 次 AI 額度</span><button className="text-link" onClick={()=>setShowHistory(v=>!v)}><History size={17}/>過去的小心事</button></div>{showHistory?<div className="card history-list">{history.filter(h=>h.mode===mode).length?history.filter(h=>h.mode===mode).map(h=><button key={h.id} onClick={()=>{setResult(h);setShowHistory(false);}}>{new Date(h.created_at).toLocaleDateString('zh-TW')} · {h.context.slice(0,30)||'毛孩的小心事'}<ArrowRight size={16}/></button>):<p>還沒有紀錄，第一個小故事正等著你。</p>}</div>:null}{busy?<div className="card empty"><Lulu state={mode==='sound'?'translating':'thinking'}/><Busy/><p>正在仔細看、輕輕聽。可能需要一些時間。</p></div>:result?<><ReportView report={result.result}/><button className="button secondary" onClick={()=>setResult(null)}><RotateCcw size={16}/>再聊一個小日常</button></>:<section className="card form"><fieldset><legend>這次，想聽誰的心事？{mode==='coexist'?'（至少兩隻）':''}</legend><div className="tag-options">{pets.map(p=><label className={ids.includes(p.id)?'selected':''} key={p.id}><input type={mode==='coexist'?'checkbox':'radio'} name="pet" checked={ids.includes(p.id)} onChange={()=>setIds(current=>mode==='coexist'?(current.includes(p.id)?current.filter(id=>id!==p.id):[...current,p.id].slice(0,4)):[p.id])}/>{p.name}</label>)}</div></fieldset>{mode==='personality'?<div className="notice">請在下方描述實際行為與相處情境；資訊不足時不會僅憑照片推論個性。<Link to="/pets" className="text-link">先更新毛孩檔案 →</Link></div>:null}{mode==='emotion'||mode==='heart'||mode==='sound'?<MediaPicker kind={mode==='sound'?'audio':'visual'} onChange={setMedia}/>:null}<label>告訴小嚕，當時發生了什麼{mode==='personality'?'（選填）':''}<textarea rows={4} maxLength={5000} value={context} onChange={e=>setContext(e.target.value)} placeholder={mode==='coexist'?'誰先靠近？有沒有食物、玩具或躲藏空間？這個情況多久了？':'在什麼地方？剛剛做了什麼？平常也會這樣嗎？'}/></label><label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意將本次內容與所選毛孩背景交由 OpenAI 分析，了解結果為推測與情境模擬，非動物語言翻譯或醫療診斷。</label><button className="button dark" disabled={!consent||!ids.length||(mode==='coexist'&&ids.length<2)||((mode==='emotion'||mode==='sound')&&!mediaIds.length)} onClick={()=>void submit()}>請小嚕聽聽 <ArrowRight size={18}/></button></section>}{error?<Notice kind="error">{error}</Notice>:null}</div>;
}
