import { useEffect,useState,useRef } from 'react';
import { Send,Plus,MessageCircle } from 'lucide-react';
import { useApp } from './Context';
import { api } from './lib';
import { PageTitle,Gate,Notice,Lulu,Busy,PetSwitch } from './components';
import type { Message,ChatSession } from './shared';
export default function Chat(){const {selected}=useApp();return <><PageTitle eyebrow="A LITTLE CONVERSATION" title="我想問問你。">那些想問牠的話，這裡都能慢慢說。</PageTitle><PetSwitch/><Gate><Conversation key={selected}/></Gate></>;}
function Conversation(){const {selected,pets}=useApp();const pet=pets.find(p=>p.id===selected);const [sessions,setSessions]=useState<ChatSession[]>([]);const [sessionId,setSessionId]=useState<string|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [question,setQuestion]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(selected)api<ChatSession[]>(`sessions&pet=${selected}`).then(setSessions).catch(e=>setError(e.message));},[selected]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});},[messages,busy]);
 async function load(id:string|null){setSessionId(id);setError('');if(!id){setMessages([]);return;}setLoading(true);try{setMessages(await api<Message[]>(`messages&session=${id}`));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function send(){if(!question.trim()||busy||!consent)return;setBusy(true);setError('');try{const data=await api<{session_id:string;messages:Message[]}>('chat','POST',{pet_id:selected,session_id:sessionId,question,consent});setSessionId(data.session_id);setMessages(m=>[...m,...data.messages]);setQuestion('');setSessions(await api<ChatSession[]>(`sessions&pet=${selected}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="chat-layout"><aside className="card chat-history"><button className="button secondary" disabled={busy||loading} onClick={()=>void load(null)}><Plus size={17}/>開始新的對話</button><h3>和{pet?.name}的聊天</h3>{sessions.length?sessions.map(s=><button disabled={busy||loading} className={sessionId===s.id?'selected':''} key={s.id} onClick={()=>void load(s.id)}><MessageCircle size={15}/>{s.title}</button>):<p className="fine">還沒有聊天紀錄。</p>}</aside><section className="card chat-main"><div className="chat-top"><span className="online-dot"/><strong>小嚕陪你，聊聊{pet?.name}</strong><span className="pill">AI 陪伴</span></div><div className="messages" aria-live="polite">{loading?<Busy/>:messages.length?messages.map(m=><div key={m.id} className={`message ${m.role}`}><span className="message-author">{m.role==='assistant'?'小嚕 LULU':'你'}</span><p>{m.content}</p></div>):<div className="chat-welcome"><Lulu small/><h2>今天，心裡有什麼小問號？</h2><p>我會記得{pet?.name}的日常習慣，陪你一起想想。</p><div className="quick-questions">{['牠一直跟著我，是想說什麼？','怎麼讓牠一個人在家更安心？','最近食慾變差，我該注意什麼？'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q} ↗</button>)}</div></div>}{busy?<Busy text="小嚕正在想想怎麼說…"/>:null}<div ref={bottom}/></div>{error?<Notice kind="error">{error}</Notice>:null}<form className="chat-compose" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="question">想問毛孩的話</label><textarea id="question" rows={2} maxLength={3000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={`關於${pet?.name}，我想問…`}/><button className="send-button" aria-label="傳送訊息" disabled={!consent||busy||loading||!question.trim()}><Send size={20}/></button></form><label className="checkbox-label chat-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意由 OpenAI 處理對話與毛孩背景。健康問題請尋求獸醫協助。</label></section></div>;
}
