import { useId,type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight,LoaderCircle,PawPrint,Plus,ShieldCheck } from 'lucide-react';
import { useApp } from './Context';
import type { Report } from './shared';
export function Lulu({state='companion',small=false}:{state?:'listening'|'thinking'|'happy'|'translating'|'companion';small?:boolean}){const label={listening:'小嚕正在聆聽',thinking:'小嚕正在思考',happy:'開心的小嚕',translating:'小嚕翻譯中',companion:'小嚕陪著你'}[state];const id=useId();return <div className={`lulu ${state} ${small?'small':''}`}><svg viewBox="0 0 260 260" role="img" aria-labelledby={id}><title id={id}>{label}</title><ellipse cx="127" cy="226" rx="81" ry="12" fill="#bcb4a2" opacity=".15"/><path d="M68 104C33 4 103-6 104 79Q137 69 162 85C184 39 220 67 190 110C234 184 190 228 127 224C53 232 26 170 68 104Z" fill="#fffdf9" stroke="#796e5c" strokeWidth="2.8"/><path d="M76 67Q65 26 84 36" fill="none" stroke="#f0cebc" strokeWidth="10" strokeLinecap="round"/><path d="M180 88l9-8" stroke="#f0cebc" strokeWidth="9" strokeLinecap="round"/><ellipse cx="91" cy="150" rx="13" ry="7" fill="#f4d9ca"/><ellipse cx="165" cy="150" rx="13" ry="7" fill="#f4d9ca"/>{state==='happy'?<g fill="none" stroke="#51483f" strokeWidth="3" strokeLinecap="round"><path d="M94 134q6-9 12 0M149 134q6-9 12 0"/></g>:<g fill="#51483f"><ellipse cx="100" cy="134" rx="3.3" ry="4.8"/><ellipse cx="154" cy="134" rx="3.3" ry="4.8"/></g>}<path d="M118 148q8 10 17 0" fill="none" stroke="#51483f" strokeWidth="2.7" strokeLinecap="round"/><path d="M64 176q12 12 21 5M175 181q13 6 20-7" fill="none" stroke="#796e5c" strokeWidth="2.7" strokeLinecap="round"/><path d="M103 209q9-16 19-2q13-17 23 0" fill="none" stroke="#b7cbbb" strokeWidth="12" strokeLinecap="round"/></svg><span className="lulu-spark spark-one">✧</span><span className="lulu-spark spark-two">✦</span></div>;}
export function Busy({text='小嚕正在整理心事…'}:{text?:string}){return <div role="status" className="busy"><LoaderCircle size={20} className="spin"/>{text}</div>;}
export function Notice({children,kind='info'}:{children:ReactNode;kind?:'info'|'error'|'success'}){return <div role={kind==='error'?'alert':'status'} className={`notice ${kind}`}>{children}</div>;}
export function PageTitle({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <header className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children?<p>{children}</p>:null}</header>;}
export function Gate({children,pet=true}:{children:ReactNode;pet?:boolean}){const {session,status,pets,loading}=useApp();if(loading)return <Busy/>;if(!status?.database)return <div className="empty card"><Lulu small/><h2>小嚕的家，正在準備中</h2><p>帳號與私有資料庫尚未連線，完成連線後就能開始。你的資料不會被假裝儲存。</p><Link className="text-link" to="/settings">查看服務狀態 <ArrowUpRight size={16}/></Link></div>;if(!session)return <div className="empty card"><Lulu small/><h2>先認識你，再認識毛孩</h2><p>登入後，毛孩的故事與每次對話都會好好保存。</p><Link className="button" to="/login">登入 / 建立帳號</Link></div>;if(pet&&!pets.length)return <div className="empty card"><Lulu small/><h2>把第一位小家人介紹給小嚕吧</h2><p>建立毛孩檔案，讓每次陪伴更懂牠。</p><Link className="button" to="/pets/new"><Plus size={18}/>新增毛孩</Link></div>;return <>{children}</>;}
export function PetSwitch(){const {pets,selected,select}=useApp();return <div className="pet-switch" aria-label="切換毛孩">{pets.map(p=><button key={p.id} className={`pet-chip ${selected===p.id?'chosen':''}`} onClick={()=>select(p.id)} aria-pressed={selected===p.id}><span className="avatar"><PawPrint size={17}/></span>{p.name}</button>)}<Link to="/pets/new" className="pet-chip add"><Plus size={16}/>{pets.length?'新增':'新增我的毛孩'}</Link></div>;}
export function ReportView({report}:{report:Report}){return <article className="report"><section className="heart-card"><span className="eyebrow">A LITTLE VOICE, A LOT OF LOVE</span><h2>牠的小心事</h2><span className="pill">AI 情境模擬</span><p className="heart-text">「{report.heart}」</p></section>{([{title:'小嚕的觀察筆記',items:report.observations},{title:'可能的情緒與行為解讀',items:report.interpretations},{title:'飼主陪伴建議',items:report.suggestions}]).map((s,i)=><section className="card report-section" key={s.title}><span className="step">0{i+1}</span><h3>{s.title}</h3><ul>{s.items.map((item,j)=><li key={j}>{item}</li>)}</ul></section>)}<section className="notice"><ShieldCheck size={20}/><div><strong>還有一些，小嚕無法確定</strong><p>{report.uncertainty}</p><p>{report.safety}</p></div></section></article>;}
