import React,{ Suspense,lazy,useEffect,useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter,Routes,Route,NavLink,Link,useLocation,Navigate } from 'react-router-dom';
import { Home as HomeIcon,MessageCircle,BookOpen,PawPrint,Settings as SettingsIcon,ArrowDownToLine } from 'lucide-react';
import { Provider,useApp } from './Context';
import { Busy,Notice } from './components';
import Home from './Home';
import './styles.css';
const Analyze=lazy(()=>import('./Analyze'));const Chat=lazy(()=>import('./Chat'));const Learn=lazy(()=>import('./Learn'));const Pets=lazy(()=>import('./Pets').then(m=>({default:m.Pets})));const PetEditor=lazy(()=>import('./Pets').then(m=>({default:m.PetEditor})));const Settings=lazy(()=>import('./Settings').then(m=>({default:m.Settings})));const Login=lazy(()=>import('./Settings').then(m=>({default:m.Login})));const Legal=lazy(()=>import('./Settings').then(m=>({default:m.Legal})));
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const nav=[{to:'/',label:'首頁',icon:HomeIcon},{to:'/chat',label:'AI 溝通',icon:MessageCircle},{to:'/learn',label:'毛孩相處學',icon:BookOpen},{to:'/pets',label:'我的毛孩',icon:PawPrint}];
function Shell(){const {session,status,error,reload}=useApp();const location=useLocation();const [install,setInstall]=useState<InstallPrompt|null>(null);useEffect(()=>{window.scrollTo(0,0);},[location.pathname]);useEffect(()=>{const receive=(e:Event)=>{e.preventDefault();setInstall(e as InstallPrompt);};window.addEventListener('beforeinstallprompt',receive);return()=>window.removeEventListener('beforeinstallprompt',receive);},[]);return <><a href="#main" className="skip-link">跳到主要內容</a><header className="site-header"><Link className="brand" to="/" aria-label="嚕哩嚕嗦 luliso. 首頁"><span className="brand-symbol">✳</span><div><span className="brand-word">luliso<span>.</span></span><span className="brand-chinese">嚕哩嚕嗦</span></div></Link><nav className="desktop-nav" aria-label="主要選單">{nav.map(n=><NavLink key={n.to} to={n.to} end={n.to==='/'}>{n.label}</NavLink>)}</nav><div className="header-actions"><span className="beta-badge">PUBLIC BETA</span><Link className="icon-button" to="/settings" aria-label="設定與資料管理"><SettingsIcon size={20} strokeWidth={1.5}/></Link>{status&&!status.publicMode?<Link className="header-login" to={session?'/pets':'/login'}>{session?'我的小家':'登入'}<ArrowDownToLine size={14}/></Link>:null}</div></header><main id="main" className="main-container">{error?<Notice kind="error">{error}<button className="text-link" onClick={reload}>重試</button></Notice>:null}<Suspense fallback={<Busy/>}><Routes><Route path="/" element={<Home/>}/><Route path="/analyze/:mode" element={<Analyze/>}/><Route path="/chat" element={<Chat/>}/><Route path="/learn" element={<Learn/>}/><Route path="/pets" element={<Pets/>}/><Route path="/pets/new" element={<PetEditor/>}/><Route path="/pets/:id" element={<PetEditor/>}/><Route path="/settings" element={<Settings/>}/><Route path="/login" element={!status?<Busy/>:status.publicMode?<Navigate to="/pets" replace/>:<Login/>}/><Route path="/privacy" element={<Legal kind="privacy"/>}/><Route path="/terms" element={<Legal kind="terms"/>}/><Route path="*" element={<div className="empty"><h1>小嚕好像走錯路了。</h1><Link className="button" to="/">回到首頁</Link></div>}/></Routes></Suspense></main><footer className="site-footer"><div><span className="brand-word">luliso.</span><p>A LITTLE LANGUAGE OF LOVE</p></div><span>不懂牠的語言，也能慢慢懂牠的心。</span><div className="footer-links"><Link to="/privacy">隱私政策</Link><Link to="/terms">服務條款</Link>{install?<button onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}>安裝 APP</button>:null}</div></footer><nav className="bottom-nav" aria-label="底部分頁">{nav.map(n=><NavLink key={n.to} to={n.to} end={n.to==='/'}><n.icon size={21} strokeWidth={1.6}/><span>{n.label}</span></NavLink>)}</nav></>;}
class ErrorBoundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className="empty"><h1>小嚕需要重新整理一下。</h1><button className="button" onClick={()=>location.reload()}>重新載入</button></div>:this.props.children;}}
createRoot(document.getElementById('root')!).render(<ErrorBoundary><BrowserRouter><Provider><Shell/></Provider></BrowserRouter></ErrorBoundary>);
if('serviceWorker' in navigator)window.addEventListener('load',()=>{navigator.serviceWorker.register('/sw.js').catch(()=>{ /* Online app remains usable when installation is unavailable. */ });});
