import { useEffect,useRef,useState } from 'react';
import { Camera,Mic,Square,Upload,X } from 'lucide-react';
import { Busy,Notice } from './components';
import { imageFile,videoFrames,wavFile } from './media';
import { upload } from './lib';
type Entry={id:string;label:string};
export default function MediaPicker({kind,onChange}:{kind:'visual'|'audio'|'photo';onChange:(ids:string[])=>void}){const [entries,setEntries]=useState<Entry[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [recording,setRecording]=useState(false);const [seconds,setSeconds]=useState(0);const [preview,setPreview]=useState('');const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const canvas=useRef<HTMLCanvasElement>(null);const animation=useRef(0);const audio=useRef<AudioContext|null>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);const autoStop=useRef<ReturnType<typeof setTimeout>|null>(null);const mounted=useRef(true);
 function cleanup(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;cancelAnimationFrame(animation.current);if(audio.current){void audio.current.close();audio.current=null;}if(timer.current)clearInterval(timer.current);if(autoStop.current)clearTimeout(autoStop.current);}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(recorder.current?.state==='recording')recorder.current.stop();cleanup();};},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 async function processFile(file:File){setError('');setBusy(true);try{if(file.size>20*1024*1024)throw new Error('檔案上限為 20 MB。');const next:Entry[]=[];if(kind==='audio'){const wav=await wavFile(file);next.push({id:await upload(wav.file,wav.duration),label:'叫聲錄音'});setPreview(URL.createObjectURL(wav.file));}else if(file.type.startsWith('video/')&&kind==='visual'){const result=await videoFrames(file);next.push({id:await upload(file,result.duration),label:'原始影片'});for(const [i,frame]of result.frames.entries())next.push({id:await upload(frame),label:`影格 ${i+1}`});setPreview(URL.createObjectURL(file));}else if(file.type.startsWith('image/')){const image=await imageFile(file);next.push({id:await upload(image),label:'照片'});setPreview(URL.createObjectURL(image));}else throw new Error('請選擇支援的照片、影片或音訊。');if(mounted.current){setEntries(next);onChange(next.map(x=>x.id));}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'媒體處理失敗。');}finally{if(mounted.current)setBusy(false);}}
 async function start(){setError('');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('此瀏覽器不支援錄製，請使用上傳。');const media=await navigator.mediaDevices.getUserMedia(kind==='visual'?{video:{facingMode:'environment'},audio:false}:{audio:true});stream.current=media;const rec=new MediaRecorder(media);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{cleanup();if(mounted.current){setRecording(false);void processFile(new File(chunks,kind==='visual'?'recording.webm':'recording.audio',{type:rec.mimeType.split(';')[0]}));}};rec.start();setSeconds(0);setRecording(true);timer.current=setInterval(()=>setSeconds(s=>s+1),1000);autoStop.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},15000);if(kind==='audio'){const ctx=new AudioContext();audio.current=ctx;const analyser=ctx.createAnalyser();analyser.fftSize=256;ctx.createMediaStreamSource(media).connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{analyser.getByteTimeDomainData(data);const el=canvas.current;if(el){const c=el.getContext('2d')!;c.clearRect(0,0,el.width,el.height);c.strokeStyle='#637e69';c.lineWidth=2;c.beginPath();data.forEach((v,i)=>{const x=i*el.width/data.length,y=v/255*el.height;if(i)c.lineTo(x,y);else c.moveTo(x,y);});c.stroke();}animation.current=requestAnimationFrame(draw);};draw();}}catch(e){cleanup();setError(e instanceof Error?e.message:'無法使用麥克風或相機，請檢查權限。');}}
 return <div className="media-picker"><div className="upload-zone"><span className="upload-icon">{kind==='audio'?<Mic size={29}/>:<Camera size={29}/>}</span><h3>{kind==='audio'?'收集一小段牠的聲音':'留住一個小小瞬間'}</h3><p>{kind==='audio'?'1–15 秒，盡量避開人聲與背景音':'照片，或 5–15 秒短影片 · 上限 20 MB'}</p><div className="button-row"><label className="button secondary"><Upload size={17}/>選擇檔案<input disabled={busy||recording} type="file" accept={kind==='audio'?'audio/*':kind==='photo'?'image/*':'image/*,video/mp4,video/webm'} onChange={e=>{const f=e.target.files?.[0];if(f)void processFile(f);e.target.value='';}} hidden/></label>{kind!=='audio'?<label className="button secondary"><Camera size={17}/>拍照<input disabled={busy||recording} type="file" accept="image/*" capture="environment" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void processFile(f);}}/></label>:null}{kind!=='photo'?<button type="button" className={`button ${recording?'danger':'secondary'}`} disabled={busy} onClick={()=>recording?recorder.current?.stop():void start()}>{recording?<Square size={15}/>:kind==='audio'?<Mic size={17}/>:<Camera size={17}/>} {recording?`停止 ${seconds}s`:kind==='audio'?'開始錄音':'錄製影片'}</button>:null}</div>{kind==='audio'?<canvas ref={canvas} width={300} height={55} aria-label="即時錄音聲波"/>:null}</div>{busy?<Busy text="正在處理並安全上傳…"/>:null}{error?<Notice kind="error">{error}</Notice>:null}{preview?<div className="media-preview">{kind==='audio'?<audio controls src={preview}/>:entries.some(e=>e.label==='原始影片')?<video controls src={preview}/>:<img src={preview} alt="待分析的毛孩照片"/>}<button type="button" className="icon-button" aria-label="移除此分析的附件" onClick={()=>{setEntries([]);setPreview('');onChange([]);}}><X size={18}/></button><p>{entries.map(e=>e.label).join(' · ')} · 已存入私有空間</p></div>:null}<p className="fine">媒體只會上傳至你的私有空間。送出分析時才交給 AI 處理；影片以 4 張離散影格分析。移除附件不會刪除原檔，可至設定管理。</p></div>;
}
