import { useState,type FormEvent } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { ArrowRight,PawPrint,Plus,Trash2 } from 'lucide-react';
import { useApp } from './Context';
import { api } from './lib';
import { Gate,PageTitle,Notice,Busy,ReportView } from './components';
import MediaPicker from './MediaPicker';
import { PetIllustration } from './PetIllustration';
import { petInput,type Pet,type PetInput } from './shared';
export function Pets(){const {pets,select}=useApp();return <><PageTitle eyebrow="MY LITTLE FAMILY" title="每一隻，都是心頭的小小你。">把牠的喜好與習慣，一點一滴收藏起來。</PageTitle><Gate pet={false}><div className="section-heading"><h2>我的毛孩 <span className="count">{pets.length}</span></h2><Link className="button" to="/pets/new"><Plus size={17}/>新增毛孩</Link></div>{!pets.length?<div className="empty card"><PawPrint size={38}/><h3>你的毛孩故事，從這裡開始</h3><p>點選「新增毛孩」，介紹你的小家人。</p></div>:<div className="pet-grid">{pets.map(p=><article className="card pet-card" key={p.id}><span className="pet-portrait"><PetIllustration species={p.species} seed={p.id} decorative/></span><span className="pill">{p.species==='cat'?'貓咪':'狗狗'}</span><h2>{p.name}</h2><p>{p.breed||'每一種可愛，都獨一無二'}</p><div className="tag-list">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="button-row"><Link className="button secondary" to={`/pets/${p.id}`}>編輯檔案</Link><Link className="text-link" to="/chat" onClick={()=>select(p.id)}>聊聊牠 <ArrowRight size={16}/></Link></div></article>)}</div>}</Gate></>;}
export function PetEditor(){const {id}=useParams();const {pets,refresh,select}=useApp();const pet=pets.find(p=>p.id===id);return <><PageTitle eyebrow="A LITTLE PERSONALITY" title={id?'那些小習慣，慢慢收藏':'你好呀，小小你。'}>個性來自相處的點滴，不由外表或生日決定。</PageTitle><Gate pet={false}>{id&&!pet?<Notice>找不到毛孩，請回到毛孩列表重試。</Notice>:<PetForm key={id||'new'} pet={pet} onSaved={async p=>{await refresh();select(p.id);}}/>}</Gate></>;}
function PetForm({pet,onSaved}:{pet?:Pet;onSaved:(p:Pet)=>Promise<void>}){const navigate=useNavigate();const {refresh}=useApp();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [photos,setPhotos]=useState(pet?.photo_ids||[]);const [remove,setRemove]=useState(false);const [confirm,setConfirm]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const form=new FormData(e.currentTarget);const input:PetInput=petInput.parse({name:form.get('name'),species:form.get('species'),birthday:form.get('birthday')||null,sex:form.get('sex'),breed:form.get('breed'),behavior:form.get('behavior'),tags:String(form.get('tags')||'').split(/[，,]/).map(t=>t.trim()).filter(Boolean),photo_ids:photos});const p=await api<Pet>(`pets${pet?`&id=${pet.id}`:''}`,pet?'PATCH':'POST',input);await onSaved(p);navigate('/pets');}catch(e){setError(e instanceof Error?e.message:'儲存失敗。');}finally{setBusy(false);}}
 async function deletePet(){if(!pet||confirm!==pet.name)return;setBusy(true);try{await api(`pets&id=${pet.id}`,'DELETE');await refresh();navigate('/pets');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="narrow"><form className="card form" onSubmit={save}><div className="form-row"><label>毛孩名字<input name="name" required maxLength={30} defaultValue={pet?.name} placeholder="怎麼稱呼你的小家人？"/></label><label>小家人的種類<select name="species" defaultValue={pet?.species||'cat'}><option value="cat">貓咪</option><option value="dog">狗狗</option></select></label></div><div className="form-row"><label>生日（可不填）<input type="date" name="birthday" max={new Date().toISOString().slice(0,10)} defaultValue={pet?.birthday||''}/></label><label>性別<select name="sex" defaultValue={pet?.sex||'unknown'}><option value="unknown">不指定</option><option value="male">男生</option><option value="female">女生</option></select></label></div><label>品種（可不填）<input name="breed" maxLength={80} defaultValue={pet?.breed} placeholder="米克斯、英國短毛貓…"/></label><label>一起生活時，你觀察到什麼？<textarea name="behavior" required minLength={10} maxLength={3000} rows={6} defaultValue={pet?.behavior} placeholder="遇到陌生人會怎麼做？最喜歡什麼互動？獨處、吃飯和玩耍時有什麼習慣？請依真實觀察描述。"/></label><label>你的個性標籤<input name="tags" defaultValue={pet?.tags.join('，')} placeholder="愛撒嬌，慢熟，好奇（以逗號分隔，最多 8 個）"/></label><fieldset><legend>正面、側面、全身照片（選填）</legend><div className="photo-slots">{['正面','側面','全身'].map((label,i)=><details key={label}><summary>{label} {photos[i]?'· 已加入':'· 加入照片'}</summary><MediaPicker kind="photo" onChange={ids=>setPhotos(current=>{const next=[...current];if(ids[0])next[i]=ids[0];else next.splice(i,1);return next.filter(Boolean);})}/></details>)}</div></fieldset>{error?<Notice kind="error">{error}</Notice>:null}<button className="button dark" disabled={busy}>{busy?'正在保存…':'好好保存這位小家人'}<ArrowRight size={18}/></button>{pet?<p className="fine">更新行為資訊後，舊個性推測會清除，可重新產生個性故事。</p>:null}</form>{pet?.personality?<ReportView report={pet.personality}/>:null}{pet?<section className="card danger-zone"><button className="text-link" onClick={()=>setRemove(!remove)}><Trash2 size={16}/>刪除這隻毛孩</button>{remove?<><p>會刪除檔案、相關對話與分析。媒體檔請至設定另行管理。請輸入「{pet.name}」確認。</p><input aria-label="確認毛孩名稱" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="button danger" disabled={busy||confirm!==pet.name} onClick={()=>void deletePet()}>確認刪除</button></>:null}</section>:null}{busy?<Busy text="正在儲存資料…"/>:null}</div>;
}
