import { useEffect,useState,type FormEvent } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { Cloud,LogOut,ShieldCheck,Trash2,Download } from 'lucide-react';
import { useApp } from './Context';
import { api,authClient } from './lib';
import { Gate,PageTitle,Notice,Busy } from './components';
import type { Media } from './shared';
export function Login(){const {session,status}=useApp();const navigate=useNavigate();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');useEffect(()=>{if(session)navigate('/pets',{replace:true});},[session,navigate]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const email=String(new FormData(e.currentTarget).get('email'));const client=authClient();if(!client)throw new Error('帳號服务尚未連線。');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/login`}});if(error)throw error;setMessage('登入連結已寄出，請查看信箱；若未收到，請稍候或檢查垃圾郵件。');}catch{setError('目前無法寄送登入連結，請檢查信箱或稍後再試。');}finally{setBusy(false);}}return <div className="narrow"><PageTitle eyebrow="WELCOME TO OUR LITTLE WORLD" title="歡迎回到，小小的家。">使用電子郵件登入，不用再記一組密碼。</PageTitle><form className="card form" onSubmit={submit}><label>電子郵件<input type="email" name="email" autoComplete="email" required placeholder="you@example.com"/></label><label className="checkbox-label"><input type="checkbox" required/>我已閱讀並同意<Link to="/terms">服務條款</Link>與<Link to="/privacy">隱私政策</Link>。</label><button className="button dark" disabled={busy||!status?.database}>{busy?'正在寄送…':'寄送安全登入連結'}</button>{!status?.database?<Notice>帳號服務尚未連線，暫時無法登入。</Notice>:null}{message?<Notice kind="success">{message}</Notice>:null}{error?<Notice kind="error">{error}</Notice>:null}</form></div>;}
export function Settings(){const {status,session}=useApp();return <><PageTitle eyebrow="A SAFE LITTLE HOME" title="讓每一份信任，都被好好照顧。">服務狀態、資料與隱私設定。</PageTitle><div className="narrow"><section className="card settings-card"><h2><ShieldCheck size={22}/>服務連線</h2><dl className="status-list"><div><dt>帳號與私有資料庫</dt><dd>{status?.database?'已設定':'未連線'}</dd></div><div><dt>AI 分析服務</dt><dd>{status?.ai?'已設定金鑰':'未連線'}</dd></div><div><dt>Google Drive 備份</dt><dd>{status?.drive==='configured'?'已設定，待權限檢查':'未連線'}</dd></div></dl><p className="fine">「已設定」不代表服務已完成實測。Drive 未連線時，照片與紀錄仍以私有儲存為主。</p></section><Gate pet={false}><AccountSettings/></Gate>{session?<button className="button secondary" onClick={async()=>{await authClient()?.auth.signOut();location.assign('/');}}><LogOut size={17}/>登出</button>:<Link className="button secondary" to="/login">登入帳號</Link>}<div className="legal-links"><Link to="/privacy">隱私政策</Link><Link to="/terms">服務條款</Link></div></div></>;}
function AccountSettings(){const [used,setUsed]=useState(0);const [media,setMedia]=useState<Media[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [consent,setConsent]=useState(false);const [confirmation,setConfirmation]=useState('');const [deleteMedia,setDeleteMedia]=useState<string|null>(null);const [drive,setDrive]=useState<{connected:boolean;message:string}|null>(null);const {status}=useApp();
 useEffect(()=>{Promise.all([api<{used:number}>('usage'),api<Media[]>('media')]).then(([u,m])=>{setUsed(u.used);setMedia(m);}).catch(e=>setError(e.message));},[]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="card settings-card"><h2>今天的小對話</h2><p><strong className="usage-number">{used}</strong> / 10 次</p><progress value={used} max={10}/><p className="fine">台灣時間每日午夜更新。送到 AI 的請求會計入額度，供應商失敗也可能計入。</p></section><section className="card settings-card"><h2><Cloud size={22}/>Google Drive 備份</h2><p>主要檔案保存在你的私有空間。Drive 是額外備份，只有在授權和資料夾隱私檢查通過後才會傳送。</p><button className="button secondary" disabled={busy} onClick={()=>void perform(async()=>{setDrive(await api('drive-status'));})}>檢查連線</button>{drive?<Notice>{drive.message}</Notice>:null}<label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意將我的照片、音訊、影片及分析報告備份到 LULISO 管理員的指定 Google Drive 私有資料夾。</label><button className="button secondary" disabled={busy||!consent||!drive?.connected||status?.drive!=='configured'} onClick={()=>void perform(async()=>{const r=await api<{completed:number;remaining:number}>('backup','POST',{consent});setMessage(`已備份 ${r.completed} 筆，尚有 ${r.remaining} 筆。${r.remaining?'可再次點選繼續備份。':''}`);})}>備份下一批資料</button></section><section className="card settings-card"><h2>我的私人媒體</h2>{media.length?media.map(m=><div className="media-row" key={m.id}><span>{m.mime.split('/')[0]} · {(m.size/1024/1024).toFixed(1)} MB<br/><small>{m.status==='ready'?'已儲存':'尚未完成，可清除'}</small></span>{m.url?<a className="icon-button" href={m.url} target="_blank" rel="noreferrer" aria-label="開啟私人媒體"><Download size={16}/></a>:null}<button className="icon-button" aria-label="刪除此媒體" disabled={busy} onClick={()=>setDeleteMedia(m.id)}><Trash2 size={16}/></button>{deleteMedia===m.id?<div><p>確定永久刪除此媒體與 Drive 副本？</p><button className="button danger" disabled={busy} onClick={()=>void perform(async()=>{await api(`media&id=${m.id}`,'DELETE');setMedia(items=>items.filter(x=>x.id!==m.id));setDeleteMedia(null);setMessage('媒體已刪除。');})}>確定刪除</button><button className="button secondary" onClick={()=>setDeleteMedia(null)}>取消</button></div>:null}</div>):<p>這裡還沒有照片或錄音。</p>}</section><section className="card danger-zone"><h2>刪除帳號與所有資料</h2><p>會永久刪除毛孩、聊天、報告、私人媒體及已備份的 Drive 副本。此操作無法復原。需在重新登入後 15 分鐘內完成。</p><label>輸入「刪除我的所有資料」<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button danger" disabled={busy||confirmation!=='刪除我的所有資料'} onClick={()=>void perform(async()=>{await api('account','DELETE',{confirmation});await authClient()?.auth.signOut();location.assign('/');})}>永久刪除帳號與資料</button></section>{busy?<Busy text="正在處理，請稍候…"/>:null}{error?<Notice kind="error">{error}</Notice>:null}{message?<Notice kind="success">{message}</Notice>:null}</>;
}
export function Legal({kind}:{kind:'privacy'|'terms'}){return <div className="narrow"><PageTitle eyebrow="LULISO PUBLIC BETA" title={kind==='privacy'?'隱私政策':'服務條款'}>更新日期：2026 年 10 月 9 日</PageTitle><article className="card legal">{kind==='privacy'?<><h2>我們保存什麼</h2><p>你提供的信箱、毛孩背景、照片、影片、聲音、分析及對話會用於登入、個人化陪伴與紀錄保存。請避免上傳人臉、地址或其他不必要的個人資料。</p><h2>資料流向與保存</h2><p>帳號與資料由 Supabase 處理，媒體保存在非公開儲存空間。Vercel 提供網站及 API。只有你送出 AI 分析或問答並同意後，相關內容會交給 OpenAI。我們的 API 請求關閉可選的回應儲存；供應商仍依其政策處理服務紀錄，這不等同零資料保留。</p><h2>Google Drive 備份</h2><p>預設不傳送至 Drive。你需另行同意，且管理員的 OAuth 授權、寫入能力及資料夾隱私檢查必須通過。此備份資料夾由服務管理員控制，管理員具有存取能力；不會建立公開分享連結。</p><h2>刪除與保留期間</h2><p>資料保留至你刪除，或服務停止。你可在設定刪除媒體或整個帳號；已知的 Drive 副本會一併刪除，若備份刪除失敗會顯示錯誤並可重試。供應商依各自政策管理安全日誌及災難復原備份。</p><h2>裝置與權限</h2><p>只有按下錄音或拍照才會請求權限。登入狀態由 Supabase 保存在裝置中；共用裝置請使用完畢後登出。離線快取不保存私人分析、聊天或媒體。</p><h2>聯絡與資料請求</h2><p>可使用設定的資料刪除入口。其他隱私問題請透過 <a href="https://github.com/a6668793/luliso-app/issues" target="_blank" rel="noreferrer">專案問題回報</a>提出聯絡需求，請勿在公開回報中附上私人檔案或密鑰。</p></>:<><h2>服務範圍</h2><p>LULISO 提供貓狗的日常行為觀察輔助、個性故事與 AI 陪伴。內容是有限資料下的推测，不是真正破解動物語言。第一人稱心聲皆為 AI 情境模擬。</p><h2>健康與安全</h2><p>本服務不提供獸醫診斷、治療或用藥建議。呼吸困難、抽搐、疑似中毒、無法排尿、失去意識等狀況請立即聯絡獸醫急診，不要等待 AI 回覆。</p><h2>使用規範</h2><p>請只上傳你有權使用的內容，勿騷擾、測試未授權存取或將服務用於傷害動物。未成年使用者應與監護人共同使用。</p><h2>公開測試限制</h2><p>Beta 每個帳號每日最多 10 次 AI 請求、12 隻毛孩、100 MB 媒體空間。功能可能暫停或調整，AI 結果可能有誤。請勿把此服務作為緊急通報管道。</p><h2>你的資料</h2><p>你保留你提供內容的權利，並授權服務於提供功能所需範圍處理。你可隨時透過設定刪除帳號與資料。</p></>}</article></div>;}
